mysql:
  image: mysql
  container_name: cognit_sample_mysql
  ports:
    - 33306:3306
  environment:
    MYSQL_USER: cognito
    MYSQL_PASSWORD: cognito
    MYSQL_DATABASE: cognito
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  restart: always
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  user: root
