cloud.aws.cognito:
  userPoolId: ${COGNITO_USER_POOL_ID}
  clientId: ${COGNITO_CLIENT_ID}
  kid: ${COGNITO_KID}

spring:
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: mysql
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/cognito
    username: cognito
    password: cognito
