cloud.aws.cognito:
  userPoolId:
  clientId:
  kid:

spring:
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: mysql
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/cognito
    username: cognito
    password: cognito
